### PR TITLE
Feature/voip

### PR DESCRIPTION
**Pull request by kondanta**
- Logic: 
  + Doctor patient relationship on video chat menu
  + Shows only patient's assigned doctors on VoIP
- Design:
  + Basic design

### CODE REVIEW

**Comment by sasalx** [comment]
Can you provide a ss for the design?

**Comment by kondanta** [comment]
sorry but i can't.

**Comment by sasalx** [comment]
Well, that's unfortunate... Let's assume you did a good job since I can't test any of this because of the VoIP server.

**Review by sasalx — APPROVED** [review]

**Comment by kondanta** [comment]
There's nothing you can't test because of the server. Server itself is an open source project. Plus, AFAIK, you already have that server anyway. I believe i did great job so..

**Comment by sasalx** [comment]
I was talking about the server that is built on your Rpi.

**Comment by kondanta** [comment]
There's no server running on my Rpi currently?

**Comment by sasalx** [comment]
Stop arguing for the sake of argument. You know what I am saying.

**Comment by kondanta** [comment]
Firstly, I'm not arguing for the sake of an argument, you're throwing excuses without having a basis. Secondly, I don't know what the heck are you talking about. Anyway.

**Pull request merged**
